export const selectors = {
    contactUsBtn: "div.links-buttons > a.fancybox > button",
    contactUsForm: "div.popup_form",
    contactUsNameInputField: "input[name='your-name']",
    contactUsEmailInputField: "input[name='your-email']",
    contactUsMobileInputField: "input[name='mobile-number']",
    contactUsSubjectInputField: "input[name='your-subject']",
    contactUsMessageInputField: "textarea[name='your-message']",
    contactUsSendBtn: "input[value='Send']",
    contactUsInvalidEmailErrorMsg: "form > p:nth-child(4) > span > span",
    companyMenuFromHomepage: ".menu-main-nav-container > .nav > .menu-item-887 > a",
    companyMenuLeadershipSection: ".company-members",
    companyFacebookIcon: ".links-buttons > a:nth-child(5)",
    careersMenuFromHomepage: ".menu-main-nav-container > .nav > .menu-item-478 > a",
    careersCheckOpenPositionsBtn: "section > div > a > button",
    careersFilterLocationDdl: "#get_location",
    careersOpenPositionCard: "article:nth-child(2) > div > a",
    openPositionGeneralDesc: "div:nth-child(1) > div.requirements.pull-right > div.content-title > h2",
    openPositionRequirement: "div:nth-child(1) > div.requirements.pull-left",
    openPositionResponsibilities: "div:nth-child(2) > div.requirements.pull-right",
    openPositionWhatWeOffer: "div:nth-child(2) > div.requirements.pull-left",
    openPositionApplyBtn: "input[type='button']",
    applyFormInvalidEmailErrorMsg: "form > p:nth-child(5) > span > span",
    applyFormChooseFileBtn: "#cf-4"
}